cuda_major_version:
  - "12"
  - "13"

###########################################################

# TODO: remove these in the next release, once we drop PY39 and align
# with CF global pinning.

python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
  - 3.13.* *_cp313t
  - 3.14.* *_cp314
  - 3.14.* *_cp314t
is_python_min:
  - true
  - false
  - false
  - false
  - false
  - false
  - false
  - false
is_freethreading:
  - false
  - false
  - false
  - false
  - false
  - true
  - false
  - true
is_abi3:
  - false
  - false
  - false
  - false
  - false
  - false
  - false
  - false
python_min:
  - "3.9"
